AQ-58 Test notebook for correlation matrix
YumaIshigooka/aigualerta pull request #15
Opened 2024-11-05 21:02 UTC by SuleymanHasanov

2024-11-05 21:03 UTC, SuleymanHasanov commented
@WdnLiu @YumaIshigooka please review

2024-11-06 15:07 UTC, YumaIshigooka commented
Añade `seaborn` a `requirements.txt`. Por lo general, si usas una libreria nueva, añadela a ese fichero.

2024-11-06 15:09 UTC, YumaIshigooka requested changes
Añade `seaborn` a `requirements.txt`. Por lo general, si usas una libreria nueva, añadela a ese fichero.

Edit: A parte, a poder ser, cuando cargues los datos, haz uso de la libreria pyarrow y después lo conviertes a pandas (un ejemplo es el fichero `src\data\load_data.ipynb`, que hace uso de esta librería y después la convierte a pandas con `.to_pandas()`:

```py
import pyarrow.dataset as ds

file_path = '<insertar path a los datos aquí>'

dataset = ds.dataset(file_path, format="parquet")
table = dataset.to_table()
df = table.to_pandas()
```

El motivo de esto es que `pandas` no es muy eficiente, y para ordenadores de bajas specs funciona bastante mal.

2024-11-06 15:30 UTC, WdnLiu commented
> Añade `seaborn` a `requirements.txt`. Por lo general, si usas una libreria nueva, añadela a ese fichero.
> 
> Edit: A parte, a poder ser, cuando cargues los datos, haz uso de la libreria pyarrow y después lo conviertes a pandas. Un ejemplo es el fichero `src\data\load_data.ipynb`, que hace uso de esta librería y después la convierte a pandas con `.to_pandas()`:
> 
> ```python
> import pyarrow.dataset as ds
> 
> file_path = '<insertar path a los datos aquí>'
> 
> dataset = ds.dataset(file_path, format="parquet")
> table = dataset.to_table()
> df = table.to_pandas()
> ```
> 
> El motivo de esto es que `pandas` no es muy eficiente, y para ordenadores de bajas specs funciona bastante mal.

Buen punto, aún así ya me parece bien dejarlo así puesto que usaremos este fichero como template para más adelante, así que el código de ejemplo que ha dejado ya es suficiente, imo

2024-11-06 16:21 UTC, closed without merging