AQ-103 user interface
YumaIshigooka/aigualerta pull request #21
Opened 2024-11-09 17:30 UTC by AdriaLeon

2024-11-09 18:14 UTC, WdnLiu requested changes
borra el notebook, que está dentro de src

2024-11-09 18:14 UTC, WdnLiu commented on src/data/load_data.ipynb
Este fichero no debería de existir, hemos movido todos los notebooks al directorio notebooks. Aún así, diría que ya ha sido subido en alguna mr anterior no?

2024-11-09 18:14 UTC, WdnLiu commented on src/user_input.py
podrías añadir tests para este fichero porfa?

2024-11-09 18:40 UTC, YumaIshigooka requested changes
Mete `streamlit` en `requirements.txt`

2024-11-09 18:44 UTC, YumaIshigooka commented on src/user_input.py
?

2024-11-10 00:30 UTC, WdnLiu requested changes
Por favor declara los nombres de las columnas en constantes, en vez de hardcodearlo en las funciones. Lo del main, no estoy seguro, pero igual se tiene que hacer en un fichero separado por eso de que se tiene que inicializar la aplicación en alguna parte, y no puede haber varios mains en un mismo proyecto

2024-11-11 15:36 UTC, WdnLiu approved these changes
Queda como deuda técnica

2024-11-11 20:31 UTC, YumaIshigooka submitted a review, later dismissed
cine

2024-11-11 20:31 UTC, YumaIshigooka commented on src/user_input.py
> +    df_deduped = df.drop_duplicates(subset='Date')[['Date', 'Pòlissa/Póliza/Policy', 'Tecnologia/Tecnología/Technology',
Que es `df_deduped`? Si eliminas todas las tuplas con el mismo "Date", las diferentes pólizas que tengan esa misma fecha serán eliminadas, cosa que es un corpontamiento no deseado.

2024-11-17 11:53 UTC, WdnLiu approved these changes

2024-11-17 12:05 UTC, MarcGutierrez approved these changes

2024-11-17 12:06 UTC, merged